#############################################################################
# Makefile for building: Partycles
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  partycles.pro
# Template: app
# Command: /opt/Qt5.7.0/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile partycles.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I../../libraries/glm-0.9.8.2 -I/opt/Qt5.7.0/5.7/gcc_64/include -I/opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/opt/Qt5.7.0/5.7/gcc_64/include/QtGui -I/opt/Qt5.7.0/5.7/gcc_64/include/QtCore -Ibuild/moc -I/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.7.0/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Partycles1.0.0
DISTDIR = /home/i7243466/devel/partycles/build/obj/Partycles1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.7.0/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/opt/Qt5.7.0/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/viewport.cpp \
		src/particleswindow.cpp build/moc/moc_viewport.cpp
OBJECTS       = build/obj/main.o \
		build/obj/viewport.o \
		build/obj/particleswindow.o \
		build/obj/moc_viewport.o
DIST          = /opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		partycles.pro include/particleswindow.h \
		include/viewport.h src/main.cpp \
		src/viewport.cpp \
		src/particleswindow.cpp
QMAKE_TARGET  = Partycles
DESTDIR       = 
TARGET        = Partycles


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: partycles.pro /opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf \
		partycles.pro \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile partycles.pro
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qml_debug.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.7.0/5.7/gcc_64/mkspecs/features/lex.prf:
partycles.pro:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile partycles.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/particleswindow.h include/viewport.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/viewport.cpp src/particleswindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/moc/moc_viewport.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_viewport.cpp
build/moc/moc_viewport.cpp: /opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QWindow \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QEvent \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QMargins \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QRect \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurface.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QScopedPointer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		include/viewport.h \
		/opt/Qt5.7.0/5.7/gcc_64/bin/moc
	/opt/Qt5.7.0/5.7/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.7.0/5.7/gcc_64/mkspecs/linux-g++ -I/home/i7243466/devel/partycles -I/home/i7243466/devel/partycles/include -I/home/i7243466/libraries/glm-0.9.8.2 -I/opt/Qt5.7.0/5.7/gcc_64/include -I/opt/Qt5.7.0/5.7/gcc_64/include/QtWidgets -I/opt/Qt5.7.0/5.7/gcc_64/include/QtGui -I/opt/Qt5.7.0/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8.5 -I/usr/include/c++/4.8.5/x86_64-redhat-linux -I/usr/include/c++/4.8.5/backward -I/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include -I/usr/local/include -I/usr/include include/viewport.h -o build/moc/moc_viewport.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp /opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QGuiApplication \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		include/particleswindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector3d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector4d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qquaternion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLBuffer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglbuffer.h \
		include/viewport.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QWindow \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QEvent \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QMargins \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QRect \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurface.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QScopedPointer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/viewport.o: src/viewport.cpp include/viewport.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QWindow \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QEvent \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QMargins \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QRect \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurface.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QScopedPointer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QCoreApplication \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLContext \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLPaintDevice \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/viewport.o src/viewport.cpp

build/obj/particleswindow.o: src/particleswindow.cpp /opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qt_windows.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector3d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qvector4d.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qquaternion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qsize.h \
		include/particleswindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLVertexArrayObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglvertexarrayobject.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QObject \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLBuffer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglbuffer.h \
		include/viewport.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QWindow \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindow.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QEvent \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QMargins \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QRect \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurface.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qicon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtCore/QScopedPointer \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		/opt/Qt5.7.0/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../libraries/glm-0.9.8.2/glm/glm.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/_fixes.hpp \
		../../libraries/glm-0.9.8.2/glm/fwd.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_int.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/setup.hpp \
		../../libraries/glm-0.9.8.2/glm/simd/platform.h \
		../../libraries/glm-0.9.8.2/glm/detail/type_float.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/precision.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat.hpp \
		../../libraries/glm-0.9.8.2/glm/vec2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/_swizzle.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/_swizzle_func.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec2.inl \
		../../libraries/glm-0.9.8.2/glm/vec3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec3.inl \
		../../libraries/glm-0.9.8.2/glm/vec4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec4.inl \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec4_simd.inl \
		../../libraries/glm-0.9.8.2/glm/mat2x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x2.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_matrix.hpp \
		../../libraries/glm-0.9.8.2/glm/mat2x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x3.inl \
		../../libraries/glm-0.9.8.2/glm/mat2x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat2x4.inl \
		../../libraries/glm-0.9.8.2/glm/mat3x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x2.inl \
		../../libraries/glm-0.9.8.2/glm/mat3x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x3.inl \
		../../libraries/glm-0.9.8.2/glm/mat3x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat3x4.inl \
		../../libraries/glm-0.9.8.2/glm/mat4x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x2.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x2.inl \
		../../libraries/glm-0.9.8.2/glm/mat4x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x3.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x3.inl \
		../../libraries/glm-0.9.8.2/glm/mat4x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x4.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x4.inl \
		../../libraries/glm-0.9.8.2/glm/detail/type_mat4x4_simd.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_matrix.inl \
		../../libraries/glm-0.9.8.2/glm/geometric.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_geometric.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_geometric.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_exponential.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec1.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_vec1.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_exponential.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_vector_relational.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_vector_relational.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_vector_relational_simd.inl \
		../../libraries/glm-0.9.8.2/glm/detail/_vectorize.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_exponential_simd.inl \
		../../libraries/glm-0.9.8.2/glm/simd/exponential.h \
		../../libraries/glm-0.9.8.2/glm/detail/func_common.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_common.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_common_simd.inl \
		../../libraries/glm-0.9.8.2/glm/simd/common.h \
		../../libraries/glm-0.9.8.2/glm/detail/func_geometric_simd.inl \
		../../libraries/glm-0.9.8.2/glm/simd/geometric.h \
		../../libraries/glm-0.9.8.2/glm/detail/func_matrix_simd.inl \
		../../libraries/glm-0.9.8.2/glm/simd/matrix.h \
		../../libraries/glm-0.9.8.2/glm/trigonometric.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_trigonometric.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_trigonometric.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_trigonometric_simd.inl \
		../../libraries/glm-0.9.8.2/glm/exponential.hpp \
		../../libraries/glm-0.9.8.2/glm/common.hpp \
		../../libraries/glm-0.9.8.2/glm/packing.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_packing.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_packing.inl \
		../../libraries/glm-0.9.8.2/glm/detail/type_half.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/type_half.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_packing_simd.inl \
		../../libraries/glm-0.9.8.2/glm/matrix.hpp \
		../../libraries/glm-0.9.8.2/glm/vector_relational.hpp \
		../../libraries/glm-0.9.8.2/glm/integer.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_integer.hpp \
		../../libraries/glm-0.9.8.2/glm/detail/func_integer.inl \
		../../libraries/glm-0.9.8.2/glm/detail/func_integer_simd.inl \
		../../libraries/glm-0.9.8.2/glm/simd/integer.h \
		../../libraries/glm-0.9.8.2/glm/gtc/matrix_transform.hpp \
		../../libraries/glm-0.9.8.2/glm/gtc/constants.hpp \
		../../libraries/glm-0.9.8.2/glm/gtc/constants.inl \
		../../libraries/glm-0.9.8.2/glm/gtc/matrix_transform.inl \
		../../libraries/glm-0.9.8.2/glm/gtc/type_ptr.hpp \
		../../libraries/glm-0.9.8.2/glm/gtc/quaternion.hpp \
		../../libraries/glm-0.9.8.2/glm/gtc/quaternion.inl \
		../../libraries/glm-0.9.8.2/glm/gtc/quaternion_simd.inl \
		../../libraries/glm-0.9.8.2/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/particleswindow.o src/particleswindow.cpp

build/obj/moc_viewport.o: build/moc/moc_viewport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_viewport.o build/moc/moc_viewport.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

